### ISSUE TITLE
herokuに反映してないよ

### ISSUE THREAD

**Issue by rkdora** [kyutech-programming-club/lt-manager#45]
たなっちの修正したやつ。
2020年度版として新しく別のherokuにあげるんだっけ？

**Comment by tanacchi** [comment]
Vue.js で作り直すっていう動きがあってだな．
完成がいつになるかわからんけど

俺の修正は使い勝手を上げるアイデアとして
糧にしてくれると思ってる

**Comment by rkdora** [comment]
なるへそ。
さんきゅー
